/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise { 'name' : string, 'muscleGroup' : MuscleGroup }
export interface ExerciseLog {
  'reps' : bigint,
  'sets' : bigint,
  'exercise' : Exercise,
  'weightKg' : number,
  'durationMin' : number,
}
export type MuscleGroup = { 'shoulders' : null } |
  { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null } |
  { 'cardio' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutGoal { 'weeklyFrequency' : bigint }
export interface WorkoutSession {
  'exercises' : Array<ExerciseLog>,
  'timestamp' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWorkoutSession' : ActorMethod<[WorkoutSession], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExercises' : ActorMethod<[], Array<Exercise>>,
  'getGoal' : ActorMethod<[], [] | [WorkoutGoal]>,
  'getPersonalRecords' : ActorMethod<[], [] | [Array<[string, number]>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutHistory' : ActorMethod<[], Array<WorkoutSession>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGoal' : ActorMethod<[WorkoutGoal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];