/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MuscleGroup = IDL.Variant({
  'shoulders' : IDL.Null,
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
  'cardio' : IDL.Null,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'muscleGroup' : MuscleGroup,
});
export const ExerciseLog = IDL.Record({
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'exercise' : Exercise,
  'weightKg' : IDL.Float64,
  'durationMin' : IDL.Float64,
});
export const Time = IDL.Int;
export const WorkoutSession = IDL.Record({
  'exercises' : IDL.Vec(ExerciseLog),
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WorkoutGoal = IDL.Record({ 'weeklyFrequency' : IDL.Nat });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWorkoutSession' : IDL.Func([WorkoutSession], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getGoal' : IDL.Func([], [IDL.Opt(WorkoutGoal)], ['query']),
  'getPersonalRecords' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setGoal' : IDL.Func([WorkoutGoal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MuscleGroup = IDL.Variant({
    'shoulders' : IDL.Null,
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'muscleGroup' : MuscleGroup,
  });
  const ExerciseLog = IDL.Record({
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'exercise' : Exercise,
    'weightKg' : IDL.Float64,
    'durationMin' : IDL.Float64,
  });
  const Time = IDL.Int;
  const WorkoutSession = IDL.Record({
    'exercises' : IDL.Vec(ExerciseLog),
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WorkoutGoal = IDL.Record({ 'weeklyFrequency' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWorkoutSession' : IDL.Func([WorkoutSession], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getGoal' : IDL.Func([], [IDL.Opt(WorkoutGoal)], ['query']),
    'getPersonalRecords' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setGoal' : IDL.Func([WorkoutGoal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };